// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtaR8AGFei63MB98o3dZglCyEjGPDyh40',
    appId: '1:160305000243:web:6651a4b9f10e49962a9846',
    messagingSenderId: '160305000243',
    projectId: 'early-cmagic',
    authDomain: 'early-cmagic.firebaseapp.com',
    storageBucket: 'early-cmagic.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfTjqa4bYD0DVyxnTpHnzkonu16nRpn8k',
    appId: '1:160305000243:android:65ca3c8a10e6b8512a9846',
    messagingSenderId: '160305000243',
    projectId: 'early-cmagic',
    storageBucket: 'early-cmagic.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTOUzhbkR3lplPe2Bib366_UmZ1qRS_CY',
    appId: '1:160305000243:ios:00ea697e25546dff2a9846',
    messagingSenderId: '160305000243',
    projectId: 'early-cmagic',
    storageBucket: 'early-cmagic.firebasestorage.app',
    iosBundleId: 'com.example.findMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTOUzhbkR3lplPe2Bib366_UmZ1qRS_CY',
    appId: '1:160305000243:ios:00ea697e25546dff2a9846',
    messagingSenderId: '160305000243',
    projectId: 'early-cmagic',
    storageBucket: 'early-cmagic.firebasestorage.app',
    iosBundleId: 'com.example.findMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtaR8AGFei63MB98o3dZglCyEjGPDyh40',
    appId: '1:160305000243:web:b24ec0fbfe8fe2ff2a9846',
    messagingSenderId: '160305000243',
    projectId: 'early-cmagic',
    authDomain: 'early-cmagic.firebaseapp.com',
    storageBucket: 'early-cmagic.firebasestorage.app',
  );
}
